# Generated by Django 5.0.8 on 2024-08-27 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='permissions',
        ),
    ]
